apiVersion: apps/v1beta2 # apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: account-service-deployment
  namespace: dev
  labels:
    app: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  
  minReadySeconds: 5
  
  template:
    metadata:
      namespace: dev
      labels:
        app: account-service
        ci: somedataForOverride1435        
    spec:
      containers:
      - name: account-service
        image: roured/tdtb-acc:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 5555
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5555
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5555
          initialDelaySeconds: 200
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 6
        envFrom:
        - configMapRef:
             name: api-urls-config  
        - secretRef:
             name: api-keys-config         
        env:
        - name: sqlCon
          valueFrom:
            secretKeyRef:
              name: db-conn-config
              key: dbAccount	

        - name: TRACING_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP        
              
        
---

kind: Service
apiVersion: v1
metadata:
  name: web-account
  namespace: dev
spec:
  selector:
    app: account-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5555 
    
---


