#Baremetal
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  externalIPs:
  - 192.168.99.100
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: ingress-nginx

---

#admin PASSWORD
kind: Service
apiVersion: v1
metadata:
  name: loghouse
  namespace: kube-system
spec:
  externalIPs:
  - 192.168.99.100
  selector:
    component: loghouse
  ports:
  - name: httpng
    port: 8200
    targetPort: 80
    protocol: TCP
---  