apiVersion: apps/v1beta2 # apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: tobuy-service-deployment
  namespace: dev
  labels:
    app: tobuy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tobuy-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  
  minReadySeconds: 5
  
  template:
    metadata:
      namespace: dev
      labels:
        app: tobuy-service
        ci: somedataForOverride1037        
    spec:
      containers:
      - name: tobuy-service
        image: roured/tdtb-tobuy:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 5555
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5555
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5555
          initialDelaySeconds: 200
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 6
        envFrom:
        - configMapRef:
             name: api-urls-config  
        - secretRef:
             name: api-keys-config	
        env:	
        - name: sqlCon
          valueFrom:
            secretKeyRef:
              name: db-conn-config
              key: dbToBuy	

        - name: TRACING_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP        
              
        
---

kind: Service
apiVersion: v1
metadata:
  name: web-tobuy
  namespace: dev
spec:
  selector:
    app: tobuy-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5555 
    
---


