#kubectl get jobs --watch
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tool-dockercheck-cron
  namespace: dev
  labels:
    app: tool-dockercheck
spec:
  schedule: "*/1 * * * *"
  
  jobTemplate:
      spec:
          template:
            metadata:
              namespace: dev
              labels:
                app: tool-dockercheck   
                ddd: dd6rdsfg6
            spec:
              restartPolicy: OnFailure
              containers:
              - name: tool-dockercheck
                image: roured/tdtb-dockercheck:dev
                imagePullPolicy: Always
                env:
                #https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/
                - name: KUBERNETES_SERVICE_HOST
                  value: "kubernetes.dev.svc.cluster.local"
                - name: KUBERNETES_SERVICE_PORT
                  value: "443"
              
        
---
