apiVersion: apps/v1beta2 # apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  
  minReadySeconds: 5
  
  template:
    metadata:
      labels:
        app: web
        ci: somedataForOverride
    spec:
      containers:
      - name: web
        image: roured/tdtb-web:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 5555
        readinessProbe:
          httpGet:
            path: /hc
            port: 5555
        
        
        
        
---

kind: Service
apiVersion: v1
metadata:
  name: web-service
spec:
  selector:
    app: web
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5555
  - name: https
    protocol: TCP
    port: 443
    targetPort: 5556   
    
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
spec:
  backend:
    serviceName: web-service
    servicePort: 80    
    
---   