# build runtime image https://hub.docker.com/r/microsoft/dotnet/tags/
#FROM microsoft/dotnet:2.0-runtime-deps
#FROM microsoft/dotnet:2.1-runtime
FROM microsoft/dotnet:2.2-runtime
WORKDIR /app
COPY ./pub-todo .
ENTRYPOINT ["dotnet", "ToDoService.dll"]