using System;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using DTO;
using Microsoft.AspNetCore.WebUtilities;
using Newtonsoft.Json;

namespace Shared
{
	//autogenerated
	public sealed partial class ToDoServiceClient
	{
	
	

	}
}