using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using DTO;
using Newtonsoft.Json;

namespace Shared
{
	//autogenerated
	public sealed partial class ToBuyServiceClient
	{
	
	

	}
}