apiVersion: apps/v1beta2 # apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: web-deployment
  namespace: dev
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  
  minReadySeconds: 5
  
  template:
    metadata:
      namespace: dev
      labels:
        app: web
        ci: somedataForOverride1531        
    spec:
      containers:
      - name: web
        image: roured/tdtb-web:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5555
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5555
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5555
          initialDelaySeconds: 10
          timeoutSeconds: 1
		envFrom:
         - configMapRef:
             name: api-urls-config  
        env:		
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: InfluxDB
          value: "http://207.244.95.62:8086"
        - name: FluentD_Host
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP  
        - name: FluentD_Port
          value: "24224"
        - name: TRACING_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP        
              
        
---

kind: Service
apiVersion: v1
metadata:
  name: web-public-main
  namespace: dev
spec:
  selector:
    app: web
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5555 
    
---


