// <auto-generated />
using System;
using AccountService.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AccountService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181228194912_LoginAttempts")]
    partial class LoginAttempts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Domain.DBEntities.UserEntity", b =>
                {
                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("IP")
                        .HasMaxLength(40);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("SaltedPwd")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<DateTime>("Updated");

                    b.HasKey("PublicId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.DBEntities.UserLoginAttemptEntity", b =>
                {
                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AtUtc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("IP")
                        .HasMaxLength(40);

                    b.HasKey("PublicId");

                    b.HasIndex("Email", "AtUtc");

                    b.ToTable("LoginAttempt");
                });
#pragma warning restore 612, 618
        }
    }
}
