//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marvin.JsonPatch.NetStandard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marvin.JsonPatch.NetStandard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property at &apos;{0}&apos; could not be copied..
        /// </summary>
        public static string CannotCopyProperty {
            get {
                return ResourceManager.GetString("CannotCopyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the property at path &apos;{0}&apos; could not be determined..
        /// </summary>
        public static string CannotDeterminePropertyType {
            get {
                return ResourceManager.GetString("CannotDeterminePropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; operation at path &apos;{1}&apos; could not be performed..
        /// </summary>
        public static string CannotPerformOperation {
            get {
                return ResourceManager.GetString("CannotPerformOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property at &apos;{0}&apos; could not be read..
        /// </summary>
        public static string CannotReadProperty {
            get {
                return ResourceManager.GetString("CannotReadProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property at path &apos;{0}&apos; could not be updated..
        /// </summary>
        public static string CannotUpdateProperty {
            get {
                return ResourceManager.GetString("CannotUpdateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression &apos;{0}&apos; is not supported. Supported expressions include member access and indexer expressions..
        /// </summary>
        public static string ExpressionTypeNotSupported {
            get {
                return ResourceManager.GetString("ExpressionTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index value provided by path segment &apos;{0}&apos; is out of bounds of the array size..
        /// </summary>
        public static string IndexOutOfBounds {
            get {
                return ResourceManager.GetString("IndexOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path segment &apos;{0}&apos; is invalid for an array index..
        /// </summary>
        public static string InvalidIndexValue {
            get {
                return ResourceManager.GetString("InvalidIndexValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; was malformed and could not be parsed..
        /// </summary>
        public static string InvalidJsonPatchDocument {
            get {
                return ResourceManager.GetString("InvalidJsonPatchDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JsonPatch operation &apos;{0}&apos;..
        /// </summary>
        public static string InvalidJsonPatchOperation {
            get {
                return ResourceManager.GetString("InvalidJsonPatchOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided path segment &apos;{0}&apos; cannot be converted to the target type..
        /// </summary>
        public static string InvalidPathSegment {
            get {
                return ResourceManager.GetString("InvalidPathSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided string &apos;{0}&apos; is an invalid path..
        /// </summary>
        public static string InvalidValueForPath {
            get {
                return ResourceManager.GetString("InvalidValueForPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is invalid for target location..
        /// </summary>
        public static string InvalidValueForProperty {
            get {
                return ResourceManager.GetString("InvalidValueForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; must be of type &apos;{1}&apos;..
        /// </summary>
        public static string ParameterMustMatchType {
            get {
                return ResourceManager.GetString("ParameterMustMatchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; which is an array is not supported for json patch operations as it has a fixed size..
        /// </summary>
        public static string PatchNotSupportedForArrays {
            get {
                return ResourceManager.GetString("PatchNotSupportedForArrays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; which is a non generic list is not supported for json patch operations. Only generic list types are supported..
        /// </summary>
        public static string PatchNotSupportedForNonGenericLists {
            get {
                return ResourceManager.GetString("PatchNotSupportedForNonGenericLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target location specified by path segment &apos;{0}&apos; was not found..
        /// </summary>
        public static string TargetLocationAtPathSegmentNotFound {
            get {
                return ResourceManager.GetString("TargetLocationAtPathSegmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For operation &apos;{0}&apos;, the target location specified by path &apos;{1}&apos; was not found..
        /// </summary>
        public static string TargetLocationNotFound {
            get {
                return ResourceManager.GetString("TargetLocationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test operation is not supported..
        /// </summary>
        public static string TestOperationNotSupported {
            get {
                return ResourceManager.GetString("TestOperationNotSupported", resourceCulture);
            }
        }
    }
}
